#!/usr/bin/env python3
"""_college_cluster.py: build the Cal / Stanford / Big Game topical cluster.

Eight pieces, four evergreen and four seasonal, each one linking up into its team hub
and across to the other programme where the subject genuinely touches both. Cards are
generated by tools/cardgen.py in the two college palettes, designed editorial cards,
no logos and no likenesses.

Nothing here is invented. Every fact was researched before writing: coaching hires,
quarterbacks, schedules, the 1892 first meeting, the 1982 Play, the Axe. Game reactions
are NOT written in advance, Stanford opens 29 August and Cal 5 September, so those two
pieces run after the games are actually played.

  python _college_cluster.py --check    report what would be written
  python _college_cluster.py            write articles + cards
"""
import os, re, sys, json, subprocess, html

ROOT = os.path.dirname(os.path.abspath(__file__))
BASE = "https://bayareasportsblog.com/"
CARDS = os.path.join(ROOT, 'assets', 'img', 'cards')

HUB = {'Cal': ('cal.html', 'Cal'), 'Stanford': ('stanford.html', 'Stanford')}

A = lambda href, text: '<a href="%s">%s</a>' % (href, text)


# --------------------------------------------------------------------------- tables

GAME_INFO = """<div class="reftable">
<table>
<caption>Stanford vs Hawaii, Week 0, 2026</caption>
<tbody>
<tr><th>Date</th><td>Saturday 29 August 2026</td></tr>
<tr><th>Kickoff</th><td class="num">4:00 p.m. PT</td></tr>
<tr><th>Venue</th><td>Stanford Stadium, Stanford, California</td></tr>
<tr><th>Television</th><td>ACC Network</td></tr>
<tr><th>Occasion</th><td>Pacific Islander heritage celebration; Cardinal Kids Day</td></tr>
<tr><th>Last meeting</th><td>Hawaii 23, Stanford 20, Week 0, 23 August 2025, in Honolulu, on a field goal as time expired</td></tr>
<tr><th>Series note</th><td>Third season-opener between the two in four years; first meeting of the current series at Stanford Stadium</td></tr>
<tr><th>2025 records</th><td>Stanford 4-8 (3-5 ACC) &middot; Hawaii 9-4, Hawaii Bowl champions</td></tr>
</tbody>
</table>
</div>"""

KEYS = """<div class="reftable">
<table>
<caption>Four things that decide it</caption>
<thead><tr><th>Key</th><th>Why it matters</th></tr></thead>
<tbody>
<tr><td>Davis Warren&rsquo;s knee</td><td>A sixth-year transfer coming off an injury, in a new offence, on a stage. Whether he steps into throws under pressure is the first honest read on Stanford&rsquo;s ceiling.</td></tr>
<tr><td>Containing Micah Alejado</td><td>3,100-plus yards and 24 touchdowns last season, two of them in this fixture. A first-year defensive staff has one game of tape on itself and none on its own communication.</td></tr>
<tr><td>The first quarter</td><td>Stanford led 10-0 early last year and lost. New staffs are often sharp on script and lost afterwards; how the second and third drives look matters more than how the first one does.</td></tr>
<tr><td>Finishing</td><td>Hawaii won this game on the final play in 2025 and won nine games doing that kind of thing. Late-game execution is the specific thing Stanford has not had.</td></tr>
</tbody>
</table>
</div>"""

SCHEDULE_TABLE = """<div class="reftable">
<table>
<caption>Stanford&rsquo;s 2026 schedule</caption>
<thead><tr><th>Date</th><th>Opponent</th><th>Site</th><th>Note</th></tr></thead>
<tbody>
<tr><td class="num">Sat 29 Aug</td><td>Hawaii</td><td>Home</td><td>Week 0; rematch of a 23-20 loss</td></tr>
<tr><td class="num">Fri 4 Sep</td><td>Miami (FL)</td><td>Home</td><td>Six days later; hardest home game</td></tr>
<tr><td class="num">Sat 19 Sep</td><td>Duke</td><td>Away</td><td>After a two-week gap</td></tr>
<tr><td class="num">Sat 26 Sep</td><td>Georgia Tech</td><td>Home</td><td>Winnable</td></tr>
<tr><td class="num">Sat 3 Oct</td><td>Wake Forest</td><td>Away</td><td>Winnable</td></tr>
<tr><td class="num">Sat 10 Oct</td><td>Notre Dame</td><td>Away</td><td>The marquee game</td></tr>
<tr><td class="num">Sat 17 Oct</td><td>Elon</td><td>Home</td><td>The only breather</td></tr>
<tr><td class="num">Fri 23 Oct</td><td>NC State</td><td>Home</td><td>Bowl-math game</td></tr>
<tr><td class="num">Sat 31 Oct</td><td>Louisville</td><td>Away</td><td>Ranked opponent</td></tr>
<tr><td class="num">Sat 14 Nov</td><td>Virginia Tech</td><td>Away</td><td>Bowl-math game</td></tr>
<tr><td class="num">Sat 21 Nov</td><td>California</td><td>Away</td><td><b>The Big Game, 129th meeting, Berkeley</b></td></tr>
<tr><td class="num">Sat 28 Nov</td><td>SMU</td><td>Home</td><td>A hard Week 13 finish</td></tr>
</tbody>
</table>
</div>"""


ARTICLES = [
# ------------------------------------------------------------------ 1. Stanford preview
dict(slug='stanford-2026-season-preview-pritchard-luck-warren',
     section='Stanford', tag='Stanford Preview', hub='Stanford',
     title='Stanford Hands the Program to Tavita Pritchard',
     h1="Stanford Hands the Keys to Tavita Pritchard, and Andrew Luck Has to Live With It",
     dek="A first-time head coach who used to hold the clipboard behind Andrew Luck, a "
         "quarterback coming off a knee injury, and a Week 0 kickoff before most of the "
         "country has unpacked its tailgate.",
     desc="Tavita Pritchard takes over on The Farm in year two of the Andrew Luck era, "
          "with Michigan transfer Davis Warren at quarterback and a Week 0 opener.",
     date='2026-08-08',
     card=('stanford', 'Stanford 2026', 'Pritchard takes over, Luck picks him, Warren throws it'),
     body=[
      "Stanford football has spent a decade being a punchline in a region that used to "
      "take it seriously, and the people running it finally seem to understand that you "
      "do not fix that with a splashy outside hire. You fix it with somebody who knows "
      "exactly how far the thing has fallen.",
      "Tavita Pritchard is that somebody. He played quarterback here from 2007 to 2010, "
      "which means he was the guy holding the clipboard while Andrew Luck turned into "
      "Andrew Luck. He came back and ran the offense from 2018 through 2022. Then he "
      "spent three years with the Washington Commanders learning what an actual "
      "professional operation looks like. Now he has his first head coaching job, at the "
      "school where he learned the game.",
      "That is a real bet, and the man making it is the interesting part. This is year "
      "two of {luck} running this programme as general manager, and he has now made the "
      "hire that defines his tenure. If Pritchard works, Luck looks like a visionary. If "
      "he does not, Luck looks like a guy who hired his old backup.",
      "The quarterback is Davis Warren, a graduate transfer out of Michigan, and this is "
      "where the optimism has to get honest. Warren is coming off a knee injury. His last "
      "season in Ann Arbor produced seven touchdown passes against nine interceptions. "
      "That is not the profile of a saviour. It is the profile of a veteran who has seen "
      "a lot of football and might keep the offense from beating itself, which, given "
      "where this programme has been, would already be progress.",
      "The schedule does not care about any of that. Stanford {opener} on 29 "
      "August against Hawaii at Stanford Stadium, the first time these two have met "
      "there, and then the ACC arrives: Duke, who won the thing, Georgia Tech, Wake "
      "Forest, Louisville, an improved Virginia Tech, SMU, and Notre Dame because "
      "Stanford will always play Notre Dame. Then {cal} in November, because some things "
      "survive every realignment.",
      "Understand what Pritchard is walking into, because the job is harder than the "
      "record makes it look. Stanford cannot recruit the way its conference rivals "
      "recruit. The admissions standards are real and they are not moving, which means "
      "every roster spot has to be found in a smaller pool than everyone else is fishing "
      "in. Then the transfer portal arrived and turned that disadvantage into a "
      "compounding one: the good players a place like this develops can be bought away, "
      "and the replacements are harder to admit. That is the actual problem, and no "
      "amount of enthusiasm about a new coach makes it go away.",
      "Which is why the NFL years matter more than the nostalgia. A staff that has "
      "watched a professional organisation operate knows how to build an offense around "
      "what it actually has rather than what it wishes it had. Washington did not hand "
      "Pritchard a roster of five-star recruits either. If there is a version of Stanford "
      "that works in this era, it looks like a team that is structurally sound, does not "
      "beat itself, and wins three or four games it has no business winning because the "
      "other side is less organised.",
      "The honest projection is that this is a season about evidence, not standings. "
      "Does the offense look designed. Does the quarterback play on time. Do the games "
      "against Duke and Notre Dame stay competitive into the fourth quarter instead of "
      "being over at halftime. Those are the questions worth watching, and the answers "
      "will tell you more about 2027 than the win total will.",
      "Nobody in Palo Alto is promising a bowl game. What they are promising is that the "
      "programme will look like it belongs to somebody again. After the last few years, "
      "that is not nothing. Full {biggame} context and the rest of our coverage sits on "
      "the {hub}.",
     ],
     links={'luck': ('andrew-luck-stanford-general-manager-experiment.html', 'Andrew Luck'),
            'opener': ('stanford-hawaii-week-zero-opener-preview.html', 'opens in Week 0'),
            'cal': ('../cal.html', 'Cal'),
            'biggame': ('big-game-cal-stanford-rivalry-history.html', 'Big Game'),
            'hub': ('../stanford.html', 'Stanford hub')},
     related=[('cal-2026-season-preview-lupoi-sagapolutele.html', 'Cal Preview', 'Tosh Lupoi Comes Home to Berkeley'),
              ('andrew-luck-stanford-general-manager-experiment.html', 'Stanford', 'Andrew Luck Is Running a Football Program'),
              ('big-game-cal-stanford-rivalry-history.html', 'Big Game', 'The Oldest Rivalry on the West Coast')]),

# ------------------------------------------------------------------ 2. Cal preview
dict(slug='cal-2026-season-preview-lupoi-sagapolutele',
     section='Cal', tag='Cal Preview', hub='Cal',
     title='Tosh Lupoi Comes Home, and Cal Might Actually Be Dangerous',
     h1="Tosh Lupoi Comes Home to Berkeley, and This Cal Team Might Actually Be Dangerous",
     dek="A first-year head coach who played on this line, a quarterback who threw for "
         "3,454 yards and came back anyway, and a schedule that misses the ACC's three "
         "biggest names.",
     desc="Tosh Lupoi takes over at Cal with Jaron-Keawe Sagapolutele returning at "
          "quarterback and an ACC schedule that misses Miami, Louisville and Florida State.",
     date='2026-08-08',
     card=('cal', 'Cal 2026', 'Lupoi comes home, Sagapolutele returns, UCLA opens it'),
     body=[
      "Every year somebody tells you Cal is going to be sneaky good and every year you "
      "believe it for about six weeks. This one is different in one specific way, and it "
      "is the way that usually matters: the quarterback came back.",
      "Jaron-Keawe Sagapolutele threw for 3,454 yards and 18 touchdowns last season and "
      "then, in an era where that profile gets a player into a bidding war by Christmas, "
      "he stayed. Whatever you think about the state of college football, a franchise "
      "quarterback choosing to remain in Berkeley is a data point about the programme "
      "that no press release can fake.",
      "The new head coach is Tosh Lupoi, and this is a homecoming. He played defensive "
      "line here. He then went and built a serious reputation as an assistant at the "
      "college and NFL levels, the kind of coach other coaches hire. Now he gets his own "
      "team, at the place he came from, which is the sort of story that either becomes a "
      "decade or becomes a cautionary tale and very rarely lands in between.",
      "What has been built around Sagapolutele is the part nobody outside the Bay is "
      "talking about: a genuine haul of receivers out of the portal, two new tackles, "
      "several backs worth handing it to, and a defence that got rebuilt rather than "
      "patched. That is not the roster of a team playing out a rebuild. That is a roster "
      "assembled by people who think the window is now.",
      "The schedule agrees. Cal opens 5 September against UCLA, then goes to Syracuse, "
      "hosts Wagner and Clemson, travels to UNLV, and takes Virginia Tech and Wake "
      "Forest at home before a November road stretch through SMU, NC State and Virginia. "
      "The season ends with {stanford} on 21 November and Pitt the week after. Look at "
      "who is missing: Miami, Louisville and Florida State are all off the card. In a "
      "conference this top-heavy, missing the three biggest names is worth more than any "
      "recruiting ranking.",
      "The Lupoi hire tells you what kind of team this is meant to be. He is a defensive "
      "line coach by trade, and defensive line coaches who become head coaches tend to "
      "build the same way: win the line of scrimmage, do not give up cheap points, make "
      "the other team's afternoon miserable. Cal has spent years being the sort of "
      "opponent that lets a superior team play comfortably. If Lupoi's first team does "
      "one thing, it should be to stop being comfortable to play against.",
      "There is a caution worth stating, because this is where every Cal preview goes "
      "wrong. A portal haul is not the same as a roster. Bringing in a pile of receivers "
      "and two tackles in one offseason means a lot of players learning a new offense at "
      "the same time, and those teams tend to look disjointed in September before they "
      "look like anything. If this team starts slowly, the temptation locally will be to "
      "declare it another false dawn by the end of the month. Do not. The schedule was "
      "built so the games that matter come later.",
      "The other thing nobody says out loud: this programme has a history of getting to "
      "five wins and stalling, and the difference between five and eight is almost "
      "always the quarterback. Cal has a quarterback. That is the entire argument for "
      "optimism, and it is a better argument than the one available in most years.",
      "Winnable home games, survivable road trips, a quarterback who wanted to be here, "
      "and a coach with something to prove in the town that raised him. If this team "
      "does not do something in 2026, the excuses are gone. The full breakdown is in our "
      "{sched}, and everything else lives on the {hub}.",
     ],
     links={'stanford': ('../stanford.html', 'Stanford'),
            'sched': ('cal-2026-schedule-game-by-game-acc.html', 'game-by-game schedule piece'),
            'hub': ('../cal.html', 'Cal hub')},
     related=[('cal-2026-schedule-game-by-game-acc.html', 'Cal', "Cal's 2026 Schedule, Game by Game"),
              ('stanford-2026-season-preview-pritchard-luck-warren.html', 'Stanford Preview', 'Stanford Hands the Keys to Tavita Pritchard'),
              ('big-game-cal-stanford-rivalry-history.html', 'Big Game', 'The Oldest Rivalry on the West Coast')]),

# ------------------------------------------------------------------ 3. Big Game (evergreen)
dict(slug='big-game-cal-stanford-rivalry-history',
     section='Bay Area', tag='Big Game', hub='both',
     title='The Big Game: The Oldest Rivalry on the West Coast',
     h1="The Big Game: How Cal and Stanford Built the Oldest Rivalry on the West Coast",
     dek="It started in 1892 with a future president as the student manager, it produced "
         "the most famous ending in the sport, and the trophy has been stolen more times "
         "than anyone at either school will admit.",
     desc="The Cal-Stanford Big Game dates to 1892, produced The Play in 1982, and is "
          "decided every November for possession of the Stanford Axe. Here is the story.",
     date='2026-08-08',
     card=('bay', 'The Big Game', 'Cal, Stanford, and the oldest rivalry on the West Coast'),
     body=[
      "Before the Apple Cup, before the Civil War up in Oregon, before USC and UCLA "
      "existed as a thing anyone argued about, there was the Big Game. Cal and Stanford "
      "first played on 19 March 1892. Stanford won 14-10. It is the oldest rivalry on "
      "this coast and it has been running, with a few interruptions, ever since.",
      "The origin story is genuinely absurd. The push for that first meeting came from "
      "Stanford's student manager, a young man named Herbert Hoover, who later found "
      "other work, and his counterpart at Cal, Herbert Lang. Two student managers named "
      "Herbert invented the defining sporting event of Northern California, and one of "
      "them ended up in the White House.",
      "The rivalry's defining moment came on 20 November 1982, in the 85th meeting. Cal "
      "led, then Stanford's quarterback, a kid named John Elway, drove them down for a "
      "field goal and what everyone assumed was the win. Four seconds left. What "
      "happened next is called, simply, The Play: five laterals on the kickoff return, "
      "Cal players pitching the ball backwards to anyone still standing, and the return "
      "man crossing the goal line through the Stanford band, which had already come onto "
      "the field to celebrate. Cal 25, Stanford 20. Elway never played in another Big "
      "Game. People at both schools have been arguing about the legality of the third "
      "lateral for more than forty years and neither side is going to concede.",
      "What they play for is the {axe}, which has its own criminal history. Since 1933 it "
      "has gone to the winner of the Big Game, and it sits in the winning school's "
      "trophy case for a year with the scores of past meetings mounted beside it.",
      "The overall ledger favours the farm. Through the 128th meeting in November 2025, "
      "Stanford leads the series 66-51-11. That is a lot of "
      "November afternoons, a lot of stolen trophies, and a lot of people who will not "
      "let it go.",
      "<b>Who has it right now.</b> Stanford. The 128th Big Game, on 22 November 2025, "
      "went to the Cardinal 31-10, two fumble returns for touchdowns, thirteen Cal "
      "penalties, and the end of a four-year run in which Berkeley kept the trophy. It "
      "was Stanford's first Big Game win since the 2020 season and its first at home "
      "since 2017. Cal goes into the 129th meeting trying to take it straight back, at "
      "home.",
      "What keeps it alive is that it was never really about football rankings. These "
      "are two universities eleven miles apart across a bay, one public and one private, "
      "one that takes forty thousand undergraduates and one that takes a fraction of "
      "that, both of them convinced the other is insufferable. The football game is just "
      "where that argument gets settled once a year in front of witnesses.",
      "That is also why the Big Game refuses to shrink when the teams are bad. There "
      "have been long stretches where neither side was going anywhere and the last "
      "Saturday still filled the stadium, because a losing season can be redeemed "
      "entirely by one afternoon. Ask anyone who was in Berkeley in 1982 what that team's "
      "record was. Nobody remembers. Everybody remembers the band.",
      "It has survived a great deal: two world wars, an era when the schools stopped "
      "speaking about eligibility rules, decades of conference reshuffling, and most "
      "recently a realignment that dragged both programmes into a conference on the "
      "other side of the country. The rivalry outlasted the Pac-12 itself. It will "
      "outlast whatever comes after the ACC too.",
      "In 2026 the Big Game lands on 21 November, in Berkeley, with new head coaches on "
      "both sidelines, {lupoi} for Cal, {pritchard} for Stanford, which is the sort of "
      "coincidence this rivalry produces roughly every generation. Our {calhub} and "
      "{stanhub} hubs carry the rest.",
     ],
     links={'axe': ('stanford-axe-trophy-history.html', 'Stanford Axe'),
            'lupoi': ('cal-2026-season-preview-lupoi-sagapolutele.html', 'Tosh Lupoi'),
            'pritchard': ('stanford-2026-season-preview-pritchard-luck-warren.html', 'Tavita Pritchard'),
            'calhub': ('../cal.html', 'Cal'),
            'stanhub': ('../stanford.html', 'Stanford')},
     related=[('stanford-axe-trophy-history.html', 'Big Game', 'The Stanford Axe and Its Criminal History'),
              ('cal-2026-season-preview-lupoi-sagapolutele.html', 'Cal Preview', 'Tosh Lupoi Comes Home to Berkeley'),
              ('stanford-2026-season-preview-pritchard-luck-warren.html', 'Stanford Preview', 'Stanford Hands the Keys to Tavita Pritchard')]),

# ------------------------------------------------------------------ 4. Realignment (evergreen)
dict(slug='cal-stanford-acc-realignment-what-changed',
     section='Bay Area', tag='College Football', hub='both',
     title='Cal and Stanford Play in the ACC Now. Here Is What That Cost.',
     h1="Cal and Stanford Play in the ACC Now, and Nobody Around Here Has Made Peace With It",
     dek="Two Bay Area schools in a conference built around the Atlantic coast. The "
         "travel is absurd, the kickoff times are worse, and the rivalry that survived "
         "it is the one nobody planned.",
     desc="What the move from the Pac-12 to the ACC actually changed for Cal and "
          "Stanford: the travel, the kickoff times, and the local rivalries that died.",
     date='2026-08-08',
     card=('bay', 'Realignment', 'Two Bay Area schools, one Atlantic Coast conference'),
     body=[
      "The Pac-12 died and the two Bay Area schools ended up in the Atlantic Coast "
      "Conference, which is a sentence that should still stop you cold. Berkeley is not "
      "on the Atlantic coast. Palo Alto is not on the Atlantic coast. Geography lost an "
      "argument with television money and this is what was left.",
      "Look at what it means in practice. {cal} spends 2026 travelling to Syracuse, "
      "Southern Methodist in Dallas, NC State in Raleigh and Virginia in Charlottesville. "
      "{stanford} draws Duke, Georgia Tech, Wake Forest, Louisville and Virginia Tech. "
      "Those are not road trips, those are deployments. A student athlete in Berkeley "
      "with a Tuesday morning lab is crossing three time zones on a Thursday.",
      "The second cost is the one nobody put in the press release: the kickoff windows. "
      "A conference whose television inventory is built around the eastern seaboard does "
      "not schedule around a Bay Area breakfast. Games that used to be Saturday "
      "afternoons in front of a full student section are now morning kicks played into a "
      "half-empty stadium, because the audience that matters is four hours ahead.",
      "And the third cost is the rivalries. The annual dates against Oregon, against "
      "Washington, against the Los Angeles schools, the ones that gave a Cal or "
      "Stanford season its rhythm, are gone or reduced to occasional novelties. What "
      "replaced them are opponents most Bay Area fans could not place on a map, playing "
      "for standings that mean nothing locally.",
      "Here is the part that is almost funny. The one fixture that survived all of it is "
      "the {biggame}, which nobody had to protect, because both schools moved together. "
      "The rivalry that predates every conference either school has ever belonged to "
      "outlived the conference that was supposed to house it forever. It will still be "
      "played in November, in front of people who care, while the rest of the schedule "
      "happens at nine in the morning against a team from North Carolina.",
      "The defence of the move is that it was survival, and that defence is not stupid. "
      "When the Pac-12 collapsed, the alternative for these two schools was a conference "
      "nobody had heard of or an independent schedule nobody would televise. The ACC "
      "offered relevance, even at a reduced financial share and an absurd travel bill. "
      "Given the options actually on the table, taking it was rational. That does not "
      "make it good. It makes it the least bad outcome of a process that never should "
      "have reached that point.",
      "What gets lost in the accounting is the thing that made college football matter "
      "regionally in the first place: familiarity. A rivalry is built by playing "
      "somebody every year for fifty years until the grudges are inherited. You cannot "
      "manufacture that with a rotating ACC opponent who visits Berkeley once a decade. "
      "The Bay Area is not going to develop a blood feud with Wake Forest, no matter how "
      "many times the schedule pairs them.",
      "There is a generational cost too. A kid growing up in the East Bay used to be "
      "able to watch Cal play Oregon and Washington and the Los Angeles schools, learn "
      "the map of their own conference, and care about it. That kid now watches a "
      "9am kickoff against a school three thousand miles away, and the honest question "
      "is whether they bother to keep watching at all.",
      "None of this gets undone. The money is spent and the contracts are signed. The "
      "most anyone around here can do is keep showing up for the games that still mean "
      "something, which is exactly what the {calhub} and {stanhub} sections are for.",
     ],
     links={'cal': ('cal-2026-schedule-game-by-game-acc.html', "Cal's 2026 schedule"),
            'stanford': ('stanford-2026-season-preview-pritchard-luck-warren.html', 'Stanford'),
            'biggame': ('big-game-cal-stanford-rivalry-history.html', 'Big Game'),
            'calhub': ('../cal.html', 'Cal'),
            'stanhub': ('../stanford.html', 'Stanford')},
     related=[('big-game-cal-stanford-rivalry-history.html', 'Big Game', 'The Oldest Rivalry on the West Coast'),
              ('cal-2026-schedule-game-by-game-acc.html', 'Cal', "Cal's 2026 Schedule, Game by Game"),
              ('stanford-2026-season-preview-pritchard-luck-warren.html', 'Stanford Preview', 'Stanford Hands the Keys to Tavita Pritchard')]),

# ------------------------------------------------------------------ 5. Luck GM (evergreen)
dict(slug='andrew-luck-stanford-general-manager-experiment',
     section='Stanford', tag='Stanford', hub='Stanford',
     title='Andrew Luck Is Running a Football Program. It Is Working.',
     h1="Andrew Luck Is Running a Football Program, and the Rest of College Football Should Be Watching",
     dek="A retired quarterback with a general manager title at his alma mater is either "
         "a vanity appointment or the first sane answer anyone has given to what college "
         "football turned into.",
     desc="Stanford handed Andrew Luck a general manager job nobody else in college "
          "football has. Here is why the structure matters more than the name on it.",
     date='2026-08-08',
     card=('stanford', 'The Luck Experiment', 'A general manager job that does not exist anywhere else'),
     body=[
      "When Stanford gave Andrew Luck a general manager title, the easy read was that a "
      "rich school had found a job for a beloved alum. The harder read, and the correct "
      "one, is that Stanford looked at what college football had become and decided it "
      "needed the one thing the sport had never bothered to build: somebody whose "
      "actual job is the roster.",
      "Think about what a head coach is now asked to do. Recruit high schoolers. Work "
      "the transfer portal in two windows. Manage name, image and likeness money like a "
      "capologist. Retain the players he already has against everyone else's money. Hire "
      "and keep a staff. And, somewhere in there, coach a football team on Saturday. "
      "Every other serious sport in the world separated those jobs decades ago.",
      "That is the experiment. Luck runs the programme, the head coach coaches. In year "
      "two, the defining move has been made: {pritchard} got the job, a first-time head "
      "coach who played quarterback here, backed Luck up, and then went and spent three "
      "years in the NFL learning how a real front office operates. That is not a "
      "sentimental hire. That is a hire that only makes sense if you believe the person "
      "picking it has thought hard about what the coach is actually for.",
      "It might not work. Stanford's admissions standards are not moving, the money in "
      "this sport is not slowing down, and no organisational chart wins you a game "
      "against Notre Dame. If the {warren} era produces four wins and nobody comes to "
      "the games, all of this reads as a very smart plan that lost anyway.",
      "It is worth being precise about why the structure helps rather than just "
      "sounding modern. A head coach evaluating a transfer is evaluating a player he "
      "will have to coach, which biases him toward players who fit what he already "
      "runs. A general manager evaluating the same player is asking a different "
      "question: what does this roster need in eighteen months, and what is this player "
      "worth against everyone else available at that price. Those are different jobs "
      "with different time horizons, and asking one person to hold both in his head "
      "during a season is how programmes end up with expensive rosters that do not fit "
      "together.",
      "The second advantage is continuity. Coaches get fired. If the roster function "
      "lives with the coach, a firing resets everything, recruiting relationships, "
      "portal strategy, the money structure, all of it. If it lives with a general "
      "manager, a coaching change is a coaching change rather than a demolition. For a "
      "programme that has already been through several resets, that alone might be "
      "worth the experiment.",
      "The scepticism is fair too. Luck has never done this before. Being a great "
      "quarterback tells you nothing about whether someone can value a left tackle "
      "against a slot receiver under a budget. And there is a version of this where the "
      "title is mostly a fundraising device and the real decisions get made the way they "
      "always were. Two years in, the Pritchard hire is the first piece of hard evidence "
      "either way.",
      "But if it does work, if separating the roster job from the coaching job turns a "
      "programme that had genuinely bottomed out back into something, then a lot of "
      "athletic directors are going to find themselves explaining why they still have "
      "one exhausted man doing five jobs. That is why this is worth watching from "
      "Berkeley, from Eugene, from anywhere. The rest of our coverage is on the {hub}.",
     ],
     links={'pritchard': ('stanford-2026-season-preview-pritchard-luck-warren.html', 'Tavita Pritchard'),
            'warren': ('stanford-2026-season-preview-pritchard-luck-warren.html', 'Davis Warren'),
            'hub': ('../stanford.html', 'Stanford hub')},
     related=[('stanford-2026-season-preview-pritchard-luck-warren.html', 'Stanford Preview', 'Stanford Hands the Keys to Tavita Pritchard'),
              ('cal-stanford-acc-realignment-what-changed.html', 'College Football', 'Cal and Stanford Play in the ACC Now'),
              ('big-game-cal-stanford-rivalry-history.html', 'Big Game', 'The Oldest Rivalry on the West Coast')]),

# ------------------------------------------------------------------ 6. The Axe (evergreen)
dict(slug='stanford-axe-trophy-history',
     section='Bay Area', tag='Big Game', hub='both',
     title='The Stanford Axe and Its Long Criminal History',
     h1="The Stanford Axe: A Trophy With a Criminal Record Going Back to 1899",
     dek="It started as a prop at a baseball game, it has been stolen by both schools "
         "more than once, and since 1933 it has belonged to whoever wins the Big Game.",
     desc="The Stanford Axe began as a yell leader's prop in 1899, was stolen repeatedly "
          "by both schools, and has gone to the Big Game winner since 1933.",
     date='2026-08-08',
     card=('bay', 'The Axe', 'A trophy with a criminal record going back to 1899'),
     body=[
      "Most rivalry trophies are invented by a committee and handed over at midfield "
      "while nobody watches. The Stanford Axe is not that. The Axe has a rap sheet.",
      "It turns up in 1899, when a Stanford yell leader named Billy Erb brought an axe "
      "to a baseball game against Cal, apparently as a prop for chopping up blue and "
      "gold ribbon. Cal students took it. That was the beginning, not the end. For "
      "decades afterwards the Axe was less a trophy than contraband, changing hands "
      "through raids, disguises, staged accidents and a level of planning that neither "
      "school's engineering department should be proud of.",
      "Order arrived in 1933, when the two schools agreed the thing would simply go to "
      "the winner of the {biggame}. It has worked that way ever since. The axe-head sits "
      "mounted on a wooden plaque with the scores of past meetings recorded alongside "
      "it, so the trophy is also the ledger. You do not just lose the Axe. You get your "
      "loss engraved onto it and then hand it to the people who beat you.",
      "That is why the Big Game does not need a manufactured narrative in a week when "
      "neither team is going anywhere. Two programmes can be having miserable seasons "
      "and the last Saturday still decides who spends a year looking at a plaque with "
      "everyone else's results on it.",
      "The theft years deserve their own telling. This was not undergraduates walking "
      "off with a souvenir. There were organised operations on both sides, groups who "
      "planned for months, staged distractions, used tear gas on one famous occasion, "
      "and treated the recovery of a piece of sporting hardware as a matter of "
      "institutional honour. Two universities that pride themselves on producing serious "
      "people spent decades running heists against each other over an axe.",
      "The 1933 agreement is what turned a running crime into a tradition. By handing "
      "it to the winner automatically, the schools converted an object that had to be "
      "stolen into one that had to be earned, and in doing so gave the Big Game a stake "
      "beyond the standings. It is a small piece of administrative genius, and it is the "
      "reason the trophy still means something ninety-odd years later while most rivalry "
      "prizes are forgotten sponsorship props.",
      "There is a lesson in it for every athletic department that has tried to "
      "manufacture a rivalry trophy in the last twenty years. You cannot invent this. "
      "The Axe works because of the century of bad behaviour behind it, not in spite of "
      "it. A trophy is only as good as the trouble people were willing to get into over "
      "it.",
      "<b>Where it is sitting today.</b> Palo Alto. Stanford won the 128th {biggame} "
      "31-10 in November 2025 and took the Axe back for the first time since the 2020 "
      "season, ending four straight years of it living in Berkeley. The plaque now "
      "carries that 31-10 alongside everything else, which is the part that stings: Cal "
      "has to look at it for a year before getting a chance to take it back.",
      "The 2026 edition, the 129th meeting, is on 21 November in Berkeley. Whichever "
      "side leaves with it, somebody is going to write about a lateral from 1982 within "
      "about ten minutes of the final whistle. Our {calhub} and {stanhub} coverage runs "
      "all season.",
     ],
     links={'biggame': ('big-game-cal-stanford-rivalry-history.html', 'Big Game'),
            'calhub': ('../cal.html', 'Cal'),
            'stanhub': ('../stanford.html', 'Stanford')},
     related=[('big-game-cal-stanford-rivalry-history.html', 'Big Game', 'The Oldest Rivalry on the West Coast'),
              ('cal-stanford-acc-realignment-what-changed.html', 'College Football', 'Cal and Stanford Play in the ACC Now'),
              ('cal-2026-season-preview-lupoi-sagapolutele.html', 'Cal Preview', 'Tosh Lupoi Comes Home to Berkeley')]),

# ------------------------------------------------------------------ 7. Cal schedule
dict(slug='cal-2026-schedule-game-by-game-acc',
     section='Cal', tag='Cal', hub='Cal',
     title="Cal's 2026 Schedule, Game by Game: Where the Season Turns",
     h1="Cal's 2026 Schedule, Game by Game, and the Four Weeks That Decide the Season",
     dek="UCLA to open, Clemson at home in September, a November road stretch that will "
         "either make this team or expose it, and the Big Game to finish.",
     desc="Every game on Cal's 2026 schedule, from the UCLA opener to the Big Game, and "
          "the stretch in October and November where the season is actually decided.",
     date='2026-08-08',
     card=('cal', "Cal's Schedule", 'UCLA to open, Clemson in September, Stanford to finish'),
     body=[
      "A schedule is not a list of dates, it is a shape. Here is the shape of Cal's 2026, "
      "and where it either becomes a season worth talking about or the usual.",
      "<b>September.</b> UCLA on the 5th to open, then a trip to Syracuse on the 12th, "
      "Wagner at home on the 19th, and Clemson on the 26th. That opener matters more "
      "than its billing, a home win over a Los Angeles school in {lupoi}'s first game "
      "sets a tone the rest of the building can feel. Clemson is the measuring stick, "
      "and nobody expects Cal to win it, which is exactly why a close one would be worth "
      "something.",
      "<b>October.</b> At UNLV on the 3rd, Virginia Tech at home on the 10th, Wake "
      "Forest at home on the 17th, then SMU in Dallas on the 24th and NC State in "
      "Raleigh on the 31st. This is the month. Two home games against beatable ACC teams "
      "in the middle, bracketed by travel. Take both home games and this is a team with "
      "a pulse in November. Split them and it is another year of almost.",
      "<b>November.</b> An open date on the 7th, Virginia on the road on the 14th, then "
      "{stanford} at home on the 21st and Pitt on the 28th to close it. The bye before a "
      "three-game finish is a gift for a first-year staff. Finishing at home in the Big "
      "Game is a better one.",
      "The thing worth noticing is who is not on here. Miami, Louisville and Florida "
      "State, three of the four names that actually decide the ACC, are all missing. "
      "In a conference this lopsided, that is worth more than any preseason ranking "
      "anyone hands out. Combine it with {qb} choosing to come back and you have the "
      "most favourable set-up Cal has been handed in years.",
      "The trap game is Wagner on 19 September, and not for the reason you think. "
      "Nobody loses that one. The risk is that it sits between Syracuse on the road and "
      "Clemson at home, which means a team with a new staff gets a week where the "
      "intensity naturally drops, immediately before the biggest home game of the "
      "non-conference schedule. Programmes that are still learning who they are have a "
      "habit of showing up flat the week after a scheduled breather.",
      "The road stretch is where the season is genuinely decided. Dallas on 24 October "
      "and Raleigh on 31 October, back to back, is the sort of two-week trip that used "
      "to be unimaginable for a Bay Area school and is now routine. Come out of it at "
      "1-1 and the bye week arrives with everything still in front of this team. Come "
      "out 0-2 and the Big Game becomes the only thing left to play for, which is not "
      "nothing around here but is not what this roster was built for.",
      "One more thing about the finish. Ending with Stanford at home and then Pitt is a "
      "genuinely strange sequence, the emotional peak of the season arrives with one "
      "game still to play. Teams have been known to win the Big Game and then no-show "
      "the following Saturday. If Cal is chasing a bowl bid in late November, that Pitt "
      "game is going to matter more than anyone wants it to.",
      "The {realign} explainer covers why a Berkeley team is playing in Raleigh at all. "
      "Everything else is on the {hub}.",
     ],
     links={'lupoi': ('cal-2026-season-preview-lupoi-sagapolutele.html', 'Tosh Lupoi'),
            'stanford': ('big-game-cal-stanford-rivalry-history.html', 'Stanford'),
            'qb': ('cal-2026-season-preview-lupoi-sagapolutele.html', 'Jaron-Keawe Sagapolutele'),
            'realign': ('cal-stanford-acc-realignment-what-changed.html', 'realignment'),
            'hub': ('../cal.html', 'Cal hub')},
     related=[('cal-2026-season-preview-lupoi-sagapolutele.html', 'Cal Preview', 'Tosh Lupoi Comes Home to Berkeley'),
              ('cal-stanford-acc-realignment-what-changed.html', 'College Football', 'Cal and Stanford Play in the ACC Now'),
              ('big-game-cal-stanford-rivalry-history.html', 'Big Game', 'The Oldest Rivalry on the West Coast')]),

# ------------------------------------------------------------------ 8. Stanford opener
dict(slug='stanford-hawaii-week-zero-opener-preview',
     section='Stanford', tag='Stanford Preview', hub='Stanford',
     title='Stanford vs Hawaii, Week 0: Preview, Keys and What to Watch',
     h1="Stanford vs Hawaii, Week 0: The Rematch Nobody at Stanford Wanted This Early",
     dek="Hawaii won this game last August on a walk-off field goal, then went 9-4 and won "
         "a bowl. They bring back the Mountain West's preseason offensive player of the "
         "year. This is not a tune-up, and Stanford has Miami six days later.",
     desc="Stanford vs Hawaii preview for Week 0 on 29 August: kickoff time, the 2025 "
          "rematch, the quarterback situations, the keys, and what each team has to prove.",
     date='2026-08-08',
     card=('stanford', 'Week 0', 'Hawaii at Stanford Stadium, 29 August, 4pm PT'),
     body=[
      "Stanford opens the {pritchard} era on 29 August against a team that beat them on "
      "the last play of this same fixture a year ago. Week 0 gets sold as a soft landing "
      "with the country watching. Look at the opponent for ten seconds and it stops "
      "looking soft.",

      GAME_INFO,

      "<b>Start with what happened last August, because it frames everything.</b> These "
      "two opened the 2025 season against each other in Honolulu and Hawaii won 23-20 on "
      "a 38-yard field goal as time expired. Stanford led 10-0 in the first quarter, "
      "including a defensive touchdown, and lost anyway. It was Hawaii's first win over "
      "Stanford after four straight defeats in the series, and their first win over a "
      "Power Four opponent since 2019. Micah Alejado threw two touchdown passes in what "
      "was only his second career start.",

      "<b>That quarterback is back, and he is now a problem.</b> Alejado threw for more "
      "than 3,100 yards with 24 touchdowns and nine interceptions in 2025 and arrives as "
      "the Mountain West preseason offensive player of the year. Hawaii finished 9-4 and "
      "won the Hawaii Bowl. They averaged roughly 394 yards and 29 points a game, almost "
      "all of it through the air, and they return Pofele Ashlock, who caught a team-high "
      "76 passes for 829 yards. Sixteen FBS transfers came in on top of that. This is a "
      "team in year five under Timmy Chang that has stopped being a plucky story and "
      "started being a good football team.",

      "<b>Now Stanford.</b> The Cardinal went 4-8 last season, 3-5 in the ACC, under "
      "Frank Reich on an interim basis. Four wins does not sound like progress and "
      "actually was: it was the programme's best since 2020 and the first time since 2015 "
      "that Stanford won more games than the year before. It ended with the 128th Big "
      "Game, a 31-10 win in which the Cardinal took back {axe} for the first time since "
      "2020. So the last thing this roster did was win a rivalry game by three "
      "touchdowns, and the first thing it has to do is beat a team that already beat it.",

      "<b>The new staff.</b> Tavita Pritchard was hired on 28 November 2025 after three "
      "seasons coaching quarterbacks for the Washington Commanders. Terry Heffernan runs "
      "the offence and Kris Richard runs the defence, both in their first season on The "
      "Farm. That is three people who have never called a game together, in their first "
      "game together, against an opponent with a returning starting quarterback and "
      "continuity everywhere. The advantage of a Week 0 stage cuts both ways.",

      "<b>Stanford's biggest question: the quarterback.</b> Davis Warren arrives from "
      "Michigan for a sixth college season and is the expected starter, with Dylan Rizk "
      "behind him and Charlie Mirer third. Warren is coming off a knee injury. Everything "
      "about Stanford's floor this season runs through whether he can stand in the pocket "
      "and throw on time without thinking about the knee, and you learn more about that "
      "on one live third down than in a month of camp reports. Nobody outside the "
      "building knows the answer yet, and anyone claiming otherwise is guessing.",

      "<b>Stanford's second question: does the offence look designed?</b> Pritchard and "
      "Heffernan are installing something from scratch. The tell is not the scoreboard, "
      "it is the first quarter, motion, spacing, whether the answers arrive before the "
      "problems do. If it looks like an NFL staff's work, that is the clearest early "
      "evidence anyone will get about whether the {luck} experiment is producing "
      "anything. If it looks like the last few years, that is evidence too.",

      "<b>Hawaii's questions are smaller but real.</b> They lost Landon Sims to expired "
      "eligibility, so Cam Barfield steps up as the lead back and the run game has to be "
      "re-established. Sixteen new FBS transfers is a lot of new faces to integrate for a "
      "team whose whole edge is continuity. And they are travelling to the mainland for a "
      "4 p.m. Pacific kickoff to play a Power Four opponent in its own stadium, the "
      "reverse of last year's arrangement, and the one situation this programme has "
      "historically found hardest.",

      "<b>The keys, honestly framed.</b> Nobody knows how this goes. What we can say is "
      "which four things will decide it.",

      KEYS,

      "<b>The schedule implication that nobody is talking about.</b> Stanford plays Miami "
      "at home on 4 September, six days after this game. Week 0 is usually a gift "
      "because it buys an extra bye; here it buys a short week into the hardest home game "
      "on the schedule. Lose to Hawaii and the season opens 0-2 with the Cardinal being "
      "written off before September is a week old. Win, and a 1-0 team gets a free swing "
      "at a ranked opponent with the whole country still paying attention. The full "
      "twelve games are on {sched}.",

      "<b>What a win would actually be worth.</b> Not a fixed decade, one game does not "
      "do that. But Week 0 has eight games on it and no competition, a new head coach's "
      "first result gets quoted for a month, and this programme has spent years being "
      "something people had opinions about rather than watched. Controlling the first "
      "sentence of the season is worth more to Stanford right now than it would be to "
      "almost anyone else.",

      "<b>And the crowd, which is not a soft point.</b> Stanford Stadium has been a "
      "difficult place to feel anything for a while. A first home game under a new staff, "
      "in a national window, with a Pacific Islander heritage celebration and Cardinal "
      "Kids Day attached to it, is exactly the sort of occasion that either starts "
      "rebuilding that or confirms the problem. The announced attendance on 29 August is "
      "a real data point about whether the Bay Area has checked back in.",

      "<b>What we are not doing.</b> Predicting a score. Hawaii won this fixture last "
      "year, returns the better quarterback and has continuity; Stanford has home field, "
      "more talent on paper and a staff nobody has scouted. Both of those are true and "
      "neither settles it. We will have the reaction after the game is played, not "
      "before.",

      "The full season is in {preview}, the twelve games are on {sched}, and the rest is "
      "on the {hub}.",
     ],
     links={'pritchard': ('stanford-2026-season-preview-pritchard-luck-warren.html', 'Tavita Pritchard'),
            'axe': ('stanford-axe-trophy-history.html', 'the Axe'),
            'luck': ('andrew-luck-stanford-general-manager-experiment.html', 'Andrew Luck'),
            'sched': ('stanford-2026-schedule-game-by-game-acc.html',
                      "the Stanford schedule page"),
            'preview': ('stanford-2026-season-preview-pritchard-luck-warren.html',
                        'our season preview'),
            'hub': ('../stanford.html', 'Stanford hub')},
     related=[('stanford-2026-schedule-game-by-game-acc.html', 'Stanford', "Stanford's 2026 Schedule, Game by Game"),
              ('stanford-2026-season-preview-pritchard-luck-warren.html', 'Stanford Preview', 'Stanford Hands the Keys to Tavita Pritchard'),
              ('andrew-luck-stanford-general-manager-experiment.html', 'Stanford', 'Andrew Luck Is Running a Football Program')]),

# -------------------------------------------------------------- 9. Stanford schedule
dict(slug='stanford-2026-schedule-game-by-game-acc',
     section='Stanford', tag='Stanford', hub='Stanford',
     title="Stanford's 2026 Schedule, Game by Game: Where the Season Turns",
     h1="Stanford's 2026 Schedule, Game by Game, and the Three Stretches That Decide It",
     dek="Hawaii in Week 0, Miami six days later, Notre Dame in October and the Big Game "
         "in Berkeley to finish. Twelve games, and a bowl bid that lives or dies in a "
         "four-week window nobody is looking at yet.",
     desc="Every game on Stanford's 2026 schedule, from the Week 0 Hawaii opener to the "
          "Big Game at Cal, and the stretch where a bowl bid is actually won or lost.",
     date='2026-08-08',
     card=('stanford', "Stanford's Schedule", 'Hawaii in Week 0, Miami in Week 1, Cal to finish'),
     body=[
      "A schedule is a shape, not a list. Here is the shape of Tavita Pritchard's first "
      "season, and the specific weeks where it becomes a bowl team or another 4-8.",

      SCHEDULE_TABLE,

      "<b>The opening is brutal and almost nobody has said so.</b> Week 0 against Hawaii "
      "on 29 August, then Miami at home on 4 September, six days later. Week 0 normally "
      "buys a team an extra week of preparation somewhere. This one buys a short week "
      "into the hardest home game on the card, against a team Stanford has no business "
      "beating on paper, in a first-year staff's second game. {opener} is the full "
      "preview of the first of those, and it is a live opponent: Hawaii won this fixture "
      "last August and went 9-4.",

      "<b>Then the schedule exhales.</b> After Miami there is no game until Duke on the "
      "road on 19 September, a two-week gap that is the single most valuable thing on "
      "this calendar for a staff installing new systems on both sides of the ball. "
      "Whatever this team looks like in September, it should look different by the end of "
      "that break. Duke away, Georgia Tech at home on the 26th, Wake Forest away on 3 "
      "October: that is the three-game stretch where a bowl bid is actually built.",

      "<b>October is the month that decides the season.</b> Notre Dame on the road on the "
      "10th is the marquee game and the one nobody expects Stanford to win. Elon at home "
      "on the 17th is the only genuine breather on the schedule. NC State at home on the "
      "23rd and Louisville away on the 31st bracket it. Take Georgia Tech, Wake Forest "
      "and NC State, three winnable ACC games, two of them at home, and this team is at "
      "four or five wins with a month to play. Split them and it is another November "
      "spent playing for pride.",

      "<b>November is short and it finishes in Berkeley.</b> Virginia Tech away on the "
      "14th, then {biggame} at Cal on the 21st, then SMU at home on the 28th. Two things "
      "about that. First, the emotional peak of the season arrives with a game still to "
      "play, and teams that win the Big Game have a long history of no-showing the "
      "following Saturday. Second, SMU is a genuinely good team to have to beat in Week "
      "13, which means a Stanford side sitting on five wins in late November has one of "
      "the least forgiving paths to a sixth that anyone will face.",

      "<b>What the ACC handed them, and what it did not.</b> Miami, Notre Dame, Louisville "
      "and SMU on one twelve-game card is not a soft draw, that is four opponents who "
      "expect to be ranked. Compare it with {calsched}, where Cal misses Miami, "
      "Louisville and Florida State entirely. Two Bay Area schools in the same conference "
      "in the same season got very different assignments, and Stanford got the harder one. "
      "{realign} explains how a Palo Alto team ended up playing in Winston-Salem and "
      "Louisville at all.",

      "<b>The travel, which is the part that does not show up in a projection.</b> Duke, "
      "Wake Forest, Notre Dame, Louisville and Virginia Tech are all road games in the "
      "eastern half of the country, and four of them fall in a seven-week span. This is "
      "the cost of realignment stated plainly: a team of students flying three time zones "
      "repeatedly during the academic term, and a coaching staff trying to build habits "
      "in a season that keeps interrupting itself.",

      "<b>The honest projection.</b> Six wins is the line worth watching, because six is "
      "a bowl and a bowl in year one would be a genuine result for a programme coming off "
      "4-8. To get there Stanford probably needs to beat Hawaii, take Elon, and win three "
      "of the Georgia Tech / Wake Forest / NC State / Virginia Tech group. That is not a "
      "fantasy and it is not comfortable either, which is roughly where this programme "
      "deserves to be projected right now.",

      "<b>How this page gets used.</b> It gets updated as results come in, so it becomes "
      "the record of the season rather than a preseason artefact. The opener is "
      "{opener}, the roster and staff are in {preview}, and the rest is on the {hub}.",
     ],
     links={'opener': ('stanford-hawaii-week-zero-opener-preview.html',
                       'our Hawaii preview'),
            'biggame': ('big-game-cal-stanford-rivalry-history.html', 'the Big Game'),
            'calsched': ('cal-2026-schedule-game-by-game-acc.html', "Cal's schedule"),
            'realign': ('cal-stanford-acc-realignment-what-changed.html',
                        'The realignment explainer'),
            'preview': ('stanford-2026-season-preview-pritchard-luck-warren.html',
                        'the season preview'),
            'hub': ('../stanford.html', 'Stanford hub')},
     related=[('stanford-hawaii-week-zero-opener-preview.html', 'Stanford Preview', 'Stanford vs Hawaii, Week 0: Preview and Keys'),
              ('stanford-2026-season-preview-pritchard-luck-warren.html', 'Stanford Preview', 'Stanford Hands the Keys to Tavita Pritchard'),
              ('cal-2026-schedule-game-by-game-acc.html', 'Cal', "Cal's 2026 Schedule, Game by Game")]),
]


def esc(s):
    return s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')


BLOCK = re.compile(r'^\s*<(table|div|ul|ol|h2|h3|figure|section)\b', re.I)


def render_body(paras, links):
    """Wrap each body item in <p>, except items that are already block-level markup
    (reference tables, lists). A <table> inside a <p> is invalid HTML."""
    out = []
    for p in paras:
        def sub(m):
            href, text = links[m.group(1)]
            return A(href, text)
        html = re.sub(r'\{(\w+)\}', sub, p)
        out.append('  ' + html.strip() if BLOCK.match(html) else '  <p>%s</p>' % html)
    return '\n\n'.join(out)


def build(a):
    slug, url = a['slug'], BASE + 'articles/' + a['slug'] + '.html'
    img = BASE + 'assets/img/cards/' + slug + '.jpg'
    hub_href, hub_name = (('../cal.html', 'Cal') if a['hub'] == 'Cal'
                          else ('../stanford.html', 'Stanford') if a['hub'] == 'Stanford'
                          else ('../bayarea.html', 'Bay Area Sports'))
    crumb_hub = ('cal.html', 'Cal') if a['hub'] == 'Cal' else \
                ('stanford.html', 'Stanford') if a['hub'] == 'Stanford' else \
                ('bayarea.html', 'Bay Area Sports')
    art = {"@context": "https://schema.org", "@type": "NewsArticle",
           "headline": a['h1'], "image": img,
           "author": {"@type": "Organization", "name": "Bay Area Sports Blog"},
           "publisher": {"@type": "Organization", "name": "Bay Area Sports Blog"},
           "description": a['desc'], "datePublished": a['date'], "dateModified": a['date'],
           "mainEntityOfPage": {"@type": "WebPage", "@id": url},
           "articleSection": a['section']}
    crumbs = {"@context": "https://schema.org", "@type": "BreadcrumbList",
              "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "Home", "item": BASE},
                {"@type": "ListItem", "position": 2, "name": crumb_hub[1],
                 "item": BASE + crumb_hub[0]},
                {"@type": "ListItem", "position": 3, "name": a['h1'], "item": url}]}
    j = lambda d: json.dumps(d, separators=(',', ':'), ensure_ascii=False)

    more = ('  <p style="margin-top:30px;color:var(--muted);font-size:15px">More coverage: '
            '<a href="%s" style="color:var(--accent2);font-weight:700">%s section</a> &middot; '
            '<a href="../bayarea.html" style="color:var(--accent2);font-weight:700">Bay Area Sports</a> &middot; '
            '<a href="../index.html" style="color:var(--accent2);font-weight:700">Bay Area Sports Blog home</a></p>'
            % (hub_href, hub_name))
    rel = '\n'.join(
        '    <a href="%s"><div class="rc">%s</div><h4>%s</h4></a>' % (h, esc(k), esc(t))
        for h, k, t in a['related'])

    return TEMPLATE % dict(
        title=esc(a['title']), desc=esc(a['desc']), url=url, img=img, h1=esc(a['h1']),
        dek=a['dek'], tag=esc(a['tag']), section=esc(a['section']),
        art=j(art), crumbs=j(crumbs), slug=slug,
        body=render_body(a['body'], a['links']), more=more, rel=rel,
        alt=esc('Bay Area Sports Blog: ' + a['h1']))


TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>%(title)s</title>
<meta name="description" content="%(desc)s">
<link rel="canonical" href="%(url)s">
<!-- fonts: preconnect + stylesheet in head (was an @import chained behind the site CSS) -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;0,9..144,700;0,9..144,900;1,9..144,500;1,9..144,700;1,9..144,900&family=Archivo:wght@400;500;600;700;800&family=Archivo+Narrow:wght@500;600;700&display=swap">
<link rel="stylesheet" href="../assets/style.css">
<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1">
<link rel="alternate" type="application/rss+xml" title="Bay Area Sports Blog" href="https://bayareasportsblog.com/feed.xml">
<meta property="og:site_name" content="Bay Area Sports Blog">
<meta property="og:locale" content="en_US">
<meta property="og:type" content="article">
<meta property="og:title" content="%(title)s">
<meta property="og:description" content="%(desc)s">
<meta property="og:url" content="%(url)s">
<meta property="og:image" content="%(img)s">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="675">
<meta property="og:image:alt" content="%(alt)s">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="%(title)s">
<meta name="twitter:description" content="%(desc)s">
<meta name="twitter:image" content="%(img)s">
<script type="application/ld+json">%(art)s</script>
<script type="application/ld+json">%(crumbs)s</script>
</head>

<body>
<header class="site-header">
  <div class="wrap hdr-top">
    <a class="brand" href="../index.html">
      <span class="mark">BA</span>
      <span class="name">Bay Area <span>Sports Blog</span><small>49ers &middot; Warriors &middot; Giants &middot; A's &middot; Sharks</small></span>
    </a>
    <button class="nav-toggle" aria-label="Menu" onclick="document.querySelector('nav.main').classList.toggle('open')">&#9776;</button>
    <nav class="main">
      <ul>
        <li><a href="../index.html">Home</a></li>
        <li><a href="../49ers.html">49ers</a></li>
        <li><a href="../warriors.html">Warriors</a></li>
        <li><a href="../giants.html">Giants</a></li>
        <li><a href="../athletics.html">A's</a></li>
        <li><a href="../sharks.html">Sharks</a></li>
        <li><a href="../cal.html">Cal</a></li>
        <li><a href="../stanford.html">Stanford</a></li>
        <li><a href="../history.html">History</a></li>
        <li><a href="../blog.html">Blog</a></li>
      </ul>
    </nav>
  </div>
</header>

<article class="article">
  <span class="tag">%(tag)s</span>
  <h1>%(h1)s</h1>
  <p style="font-size:19px;color:#cdd2db;margin:-4px 0 20px;font-style:italic">%(dek)s</p>
  <div class="byline">Bay Area Sports Blog Staff &middot; %(section)s</div>
  <picture><source type="image/webp" srcset="../assets/img/cards/%(slug)s-400w.webp 400w, ../assets/img/cards/%(slug)s-600w.webp 600w, ../assets/img/cards/%(slug)s-800w.webp 800w, ../assets/img/cards/%(slug)s.webp 1200w" sizes="(max-width: 820px) 92vw, 760px"><img src="../assets/img/cards/%(slug)s.jpg" alt="%(alt)s" width="1200" height="675" decoding="async" fetchpriority="high" srcset="../assets/img/cards/%(slug)s-400w.jpg 400w, ../assets/img/cards/%(slug)s-600w.jpg 600w, ../assets/img/cards/%(slug)s-800w.jpg 800w, ../assets/img/cards/%(slug)s.jpg 1200w" sizes="(max-width: 820px) 92vw, 760px" style="display:block;width:100%%;max-width:760px;height:auto;margin:0 auto 24px;border-radius:12px;border:1px solid var(--line)"></picture>

%(body)s

%(more)s
</article>

<section class="related">
  <h3>Related columns</h3>
  <div class="rel-grid">
%(rel)s
  </div>
</section>

<footer class="site-footer">
  <div class="foot-bottom">&copy; 2026 Bay Area Sports Blog. All rights reserved. &middot; <a href="../index.html">Home</a> &middot; <a href="../bayarea.html">Bay Area Sports</a> &middot; <a href="../about.html">About</a> &middot; <a href="../editorial-standards.html">Standards</a> &middot; <a href="../corrections.html">Corrections</a></div>
</footer>
</body>
</html>
"""


def main():
    check = '--check' in sys.argv
    for a in ARTICLES:
        p = os.path.join(ROOT, 'articles', a['slug'] + '.html')
        card = os.path.join(CARDS, a['slug'] + '.jpg')
        words = sum(len(re.sub(r'<[^>]+>', ' ', x).split()) for x in a['body'])
        links = sum(x.count('{') for x in a['body'])
        print('  %-52s %4dw  %2d links  title %2d  desc %3d'
              % (a['slug'][:52], words, links, len(a['title']), len(a['desc'])))
        if check:
            continue
        if not os.path.exists(card):
            subprocess.run([sys.executable, os.path.join(ROOT, 'tools', 'cardgen.py'),
                            a['card'][0], a['card'][1], a['card'][2], card], check=True)
        html_out = build(a)
        with open(p, 'w', encoding='utf-8', newline='') as fh:
            fh.write(html_out)
        b = open(p, 'rb').read()
        if b'\x00' in b or b.count(b'\xef\xbf\xbd'):
            raise SystemExit('corruption writing %s' % p)
    print('%s  %d articles' % ('CHECK' if check else 'WROTE', len(ARTICLES)))


if __name__ == '__main__':
    main()
